### ISSUE TITLE
Cannot execute script.

### ISSUE THREAD

**Issue by Vanderscycle** [RRRRRm/polybar-fcitx5-script#2]
Hey,

Thank you for making this bash script. I am having issues executing the script through polybar giving me the following result.

![not-working](https://github.com/RRRRRm/polybar-fcitx5-script/assets/52706578/e51321d0-88a7-4d82-9295-e68172622e1a)

```ini
[module/fcitx]
type = custom/script
exec = ~/Documents/dotFiles/.config/polybar/fcitx5.sh
tail = true
interval = 0
format-prefix = "KBD"
```
Current polybar folder structure
```bash
dotFiles/.config/polybar on  main [$!] took 18s
❯ pwd
/home/henri/Documents/dotFiles/.config/polybar

dotFiles/.config/polybar on  main [$!]
❯ ls
.rw-r--r-- 5.1k henri 18 Jul 19:44 config.ini
.rwxrwxrwx 2.1k henri 17 Jul 19:46 fcitx5.sh
.rw-------  305 henri 15 Jul 22:15 launch.sh
.rw-r--r--  774 henri 17 Jul 19:33 mocha.ini
```

Any help is appreciated. I feel the fix is simple but it evades me. 
Thank you

**Comment by Tarik366** [comment]
I don't know so much but try `exec = ~/Documents/.config/polybar/fcitx5.sh` instead `exec = ~/Documents/dotFiles/.config/polybar/fcitx5.sh` from exec path.

**Comment by Vanderscycle** [comment]
I am getting the same error but from a different dir now. I am using `nixos` so everything is symlinked.

**Comment by Tarik366** [comment]
are you setting file to executable? `chmod u+x fcitx5.sh`

**Comment by Vanderscycle** [comment]
![not-working](https://github.com/RRRRRm/polybar-fcitx5-script/assets/52706578/2bec978a-1fff-40cd-a4cd-2615e2132b26)
